baseURL = "https://marinelife2030.org/"
languageCode = "en-us"
title = "Marine Life 2030"
canonifyURLs = true

[pagination]
  pagerSize = 10

[params]
  description = "Building global knowledge of marine life for local action"
  email = "marinelife2030@gmail.com"
  twitter = "https://twitter.com/marinelife2030"
  instagram = "https://instagram.com/marinelife_2030"
  youtube = "https://www.youtube.com/channel/UC5oYhg2Ay9bn87Wn4DWyTtA/featured"
  linkedin = "https://www.linkedin.com/in/marine-life-b87a68226/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    identifier = "about"
    weight = 2
  [[menu.main]]
    name = "Ocean Decade Proposal"
    parent = "about"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Style Guide"
    parent = "about"
    url = "/style-guide/"
    weight = 2
  [[menu.main]]
    name = "News"
    identifier = "news"
    weight = 3
  [[menu.main]]
    name = "Newsroom"
    parent = "news"
    url = "/news/"
    weight = 1
  [[menu.main]]
    name = "Upcoming Events"
    parent = "news"
    url = "/upcoming-events/"
    weight = 2
  [[menu.main]]
    name = "Newsletters"
    parent = "news"
    url = "/newsletters/"
    weight = 3
  [[menu.main]]
    name = "Affiliated Projects"
    url = "/affiliated-projects/"
    weight = 4
  [[menu.main]]
    name = "Join Us"
    url = "/join-us/"
    weight = 5
